# Generated by Django 3.2.8 on 2021-10-16 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TBCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default='I7V3y1-q8Qp4hxxJ0oc-M', max_length=225, unique=True)),
                ('name', models.CharField(max_length=225)),
                ('status', models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TBSchedulers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default='gogrJv1viWAFkJ_DgsjSR', max_length=225, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TBEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('public_id', models.CharField(default='I-IRgHBIfYzZKsh5wf2Zx', max_length=225, unique=True)),
                ('name', models.CharField(max_length=225)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('country', models.CharField(max_length=225)),
                ('province', models.CharField(max_length=225)),
                ('district', models.CharField(max_length=225)),
                ('region', models.CharField(max_length=225)),
                ('organization_name', models.CharField(max_length=225)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.tbcategory')),
                ('schedulers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.tbschedulers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
